# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies without running any lifecycle scripts
RUN npm install --ignore-scripts

# Copy the rest of the code
COPY . .

# Build the project (compile TypeScript to JavaScript)
RUN npm run build

EXPOSE 3000

# Command to run the MCP server
CMD [ "npm", "start" ]
